[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build"

[deploy]
startCommand = "cd backend && npm install && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PORT = "3000"
NODE_ENV = "production"

[[services]]
name = "frontend"
internal_port = 3000
external_port = 80
auto_start = true
auto_stop = false
